version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: mon_postgres
    environment:
      POSTGRES_USER: votre_utilisateur
      POSTGRES_PASSWORD: votre_mot_de_passe
      POSTGRES_DB: votre_base_de_donnees
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
